import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const MIGRATION_ANNOTATION = /^--\s*mig:(up|down)\s+(\d{10})\s+(.+)$/;

async function main() {
  const args = process.argv.slice(2);
  const outdirIndex = args.indexOf('--outdir');
  const outputDir = outdirIndex >= 0 ? args[outdirIndex + 1] : 'autogen';
  const inputTarget = outdirIndex >= 0
    ? args.filter((_, index) => index !== outdirIndex && index !== outdirIndex + 1)[0]
    : args[0] ?? '.';

  const sourceFiles = await resolveSourceFiles(inputTarget);
  const outputContent = new Map<string, string[]>();

  for (const sourceFile of sourceFiles) {
    const fileContent = await readFile(sourceFile, 'utf8');
    appendMigrationContent(fileContent, outputContent);
  }

  await clearAutogenFiles(outputDir);

  for (const [fileName, lines] of outputContent.entries()) {
    const normalizedLines = lines[lines.length - 1] === '' ? [...lines] : [...lines, ''];
    normalizedLines.push('COMMIT;');
    await writeFile(path.join(outputDir, fileName), `${normalizedLines.join('\n')}\n`, 'utf8');
  }
}

async function resolveSourceFiles(inputTarget: string) {
  const sourcePath = path.resolve(process.cwd(), inputTarget);
  const fileStats = await readdir(path.dirname(sourcePath)).catch(() => null);

  if (fileStats === null || path.extname(sourcePath) === '.sql') {
    return [sourcePath];
  }

  const entries = await readdir(sourcePath, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.sql'))
    .map((entry) => path.join(sourcePath, entry.name))
    .sort();
}

function appendMigrationContent(fileContent: string, outputContent: Map<string, string[]>) {
  const lines = fileContent.split(/\r?\n/);
  let currentFileName = '';

  for (const line of lines) {
    const trimmedLine = line.trim();
    const annotationMatch = trimmedLine.match(MIGRATION_ANNOTATION);

    if (annotationMatch) {
      const [, direction, version, description] = annotationMatch;
      currentFileName = `${version}_${slugify(description)}.${direction}.sql`;

      if (!outputContent.has(currentFileName)) {
        outputContent.set(currentFileName, [
          '-- Code generated by internal/data/genmig.ts. DO NOT EDIT.',
          '',
          'BEGIN;',
          ''
        ]);
      }

      continue;
    }

    if (!currentFileName) {
      if (!trimmedLine) {
        continue;
      }

      throw new Error('Cannot write migration content before a mig annotation');
    }

    outputContent.get(currentFileName)?.push(line);
  }
}

async function clearAutogenFiles(outputDir: string) {
  const normalizedOutputDir = path.resolve(process.cwd(), outputDir);
  await mkdir(normalizedOutputDir, { recursive: true });

  const entries = await readdir(normalizedOutputDir, { withFileTypes: true });
  await Promise.all(
    entries
      .filter((entry) => entry.isFile() && entry.name.endsWith('.sql'))
      .map((entry) => rm(path.join(normalizedOutputDir, entry.name)))
  );
}

function slugify(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

void main();
