env: development
app_name: z-meng-backend

server:
  host: 127.0.0.1
  port: 4101

database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  db_name: z_meng
  ssl_mode: disable

runtime:
  enable_http: true
  migration_target: autoup

ai:
  provider: dashscope
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: qwen-plus
  api_key: "sk-4cf9a21b0dbc4634af5db628bf1e35e2"
