env: development
app_name: z-meng-backend

server:
  host: 127.0.0.1
  port: 4101

database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  db_name: z_meng
  ssl_mode: disable

runtime:
  enable_http: true
  migration_target: autoup

ai:
  provider: dashscope
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: qwen3.6-plus
  image_base_url: https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation
  image_model: qwen-image-2.0-pro
  api_key: "sk-4cf9a21b0dbc4634af5db628bf1e35e2"
  timeout_ms: 120000
