import fs from 'node:fs';
import path from 'node:path';

const annotationPattern = /^--+\s*mig:(up|down)\s+(\d{10})\s+(.+)$/;

function main(): void {
  const { outdir, inputs } = parseArgs(process.argv.slice(2));
  const sqlFiles = collectSqlFiles(inputs);
  const generatedContent = new Map<string, string[]>();

  for (const file of sqlFiles) {
    generateContent(file, generatedContent);
  }

  clearAutogenFiles(outdir);

  for (const [fileName, lines] of generatedContent.entries()) {
    const normalized = lines.at(-1) === '' ? [...lines] : [...lines, ''];
    normalized.push('COMMIT;');
    fs.writeFileSync(path.join(outdir, fileName), `${normalized.join('\n')}\n`, 'utf8');
  }
}

function parseArgs(args: string[]): { outdir: string; inputs: string[] } {
  let outdir = 'autogen';
  const inputs: string[] = [];

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === '--outdir') {
      outdir = args[index + 1] ?? outdir;
      index += 1;
      continue;
    }
    inputs.push(arg);
  }

  return {
    outdir,
    inputs: inputs.length === 0 ? ['.'] : inputs
  };
}

function collectSqlFiles(inputs: string[]): string[] {
  const files: string[] = [];

  for (const input of inputs) {
    const stats = fs.statSync(input);
    if (stats.isDirectory()) {
      for (const entry of fs.readdirSync(input, { withFileTypes: true })) {
        if (entry.isDirectory() || path.extname(entry.name) !== '.sql') {
          continue;
        }
        files.push(path.join(input, entry.name));
      }
      continue;
    }

    if (path.extname(input) === '.sql') {
      files.push(input);
    }
  }

  return files.sort();
}

function clearAutogenFiles(outdir: string): void {
  fs.mkdirSync(outdir, { recursive: true });

  for (const entry of fs.readdirSync(outdir, { withFileTypes: true })) {
    if (entry.isDirectory() || path.extname(entry.name) !== '.sql') {
      continue;
    }
    fs.rmSync(path.join(outdir, entry.name));
  }
}

function generateContent(filePath: string, generatedContent: Map<string, string[]>): void {
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  let currentFileName = '';

  for (const line of lines) {
    const trimmedLine = line.trim();
    const match = trimmedLine.match(annotationPattern);

    if (match) {
      const [, direction, version, description] = match;
      currentFileName = `${version}_${slugify(description)}.${direction}.sql`;

      if (!generatedContent.has(currentFileName)) {
        generatedContent.set(currentFileName, [
          '-- Code generated by migrate/genmig. DO NOT EDIT.',
          '',
          'BEGIN;',
          ''
        ]);
      }
      continue;
    }

    if (!currentFileName) {
      if (trimmedLine === '') {
        continue;
      }
      throw new Error(`Unable to write migration content before annotation in ${filePath}`);
    }

    generatedContent.get(currentFileName)?.push(line);
  }
}

function slugify(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

main();
