-- Code generated by internal/data/genmig.ts. DO NOT EDIT.

BEGIN;

DROP INDEX IF EXISTS user_projects_project_id_idx;
DROP INDEX IF EXISTS user_projects_user_id_idx;
DROP TABLE IF EXISTS user_projects CASCADE;

COMMIT;
