-- Code generated by internal/data/genmig.ts. DO NOT EDIT.

BEGIN;

CREATE TABLE IF NOT EXISTS projects
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    aspect_ratio VARCHAR(20),
    global_art_style TEXT,
    visual_asset_description JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT projects_status_check CHECK (status IN ('draft', 'in_progress', 'completed'))
);
CREATE INDEX IF NOT EXISTS projects_status_idx ON projects(status);
CREATE INDEX IF NOT EXISTS projects_deleted_at_idx ON projects(deleted_at);

COMMIT;
