-- Code generated by internal/data/genmig.ts. DO NOT EDIT.

BEGIN;

CREATE TABLE IF NOT EXISTS user_projects
(
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, project_id),
    CONSTRAINT fk_user_projects_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_projects_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS user_projects_user_id_idx ON user_projects(user_id);
CREATE INDEX IF NOT EXISTS user_projects_project_id_idx ON user_projects(project_id);

COMMIT;
