-- Code generated by internal/data/genmig.ts. DO NOT EDIT.

BEGIN;

DROP INDEX IF EXISTS projects_deleted_at_idx;
DROP INDEX IF EXISTS projects_status_idx;
DROP TABLE IF EXISTS projects CASCADE;

COMMIT;
